### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by mitchtbaum**

### CODE REVIEW

**Comment by mitchtbaum** [comment]
- https://github.com/zrkn/rlua_serde/issues/4
- https://github.com/poga/actix-lua/issues/24

**Comment by mitchtbaum** [comment]
are you going to send those rlua-serde changes to zrkn?

**Comment by mitchtbaum** [comment]
ready upstream

**Comment by dariusc93** [comment]
Implemented in 6b82726b41426081775005aaa4a3b0a57bb841c4

**Pull request closed without merging**
